language: node_js
node_js: 12
before_script:
  - npm i -g gatsby
script:
  - npm run lint
  - npm run test
after_success:
  - npm run semantic-release
  - npm run coveralls
env:
  global:
    - secure: NbRe5bB800v45CVWTXULEQdixDdCHRdy9QjFmhRK9PflrqiGn8kaBeG8rMVHQ1/KTU21miSh/wmiTYle1Y1rmZU7pQ8JKkvgeiR40YxPtNd3PzxSLZvQplYlQJRkVSDPf+BAt/dNhL8H3WkQ5vIoBCYaxMBILMIQNKCGcSRrMY6WLoHFYcHCc0mHvZkyVGr524FdLCaBkHjiv/trzdjS4t/4yH5DUQLRfRRZ1PO1FAlsR9JssexDJGPcwgRaiJCbaBI0cLbO8ZfUJtsSEc2n+xfHv/nraMH8IsMJSPcOMCFDucEckCswQUwjSBwYrmGg3ZLoRZXjrloysXYbNZGMINgZ3I8ndnjQ6Lt3WetDRKaz0Dk2enxg0L6IdWdVF0BuRkwPNc2V+Zr/Es3KCqu7pC+GGuO5doM/NPFPFkzVtNMRCEj+ZXDeuToSRRDNuSPRtbVLCxBqqcUkKHLZyLxLXMeAFV6Eiun8O4khN1WKwT9Psgev5JhOYMHmUUO07Ut4Ux+SA/V42tXjPCKB/1vSAfPc98Cfr267oQzc/fbtbyz1YbMxGmon7hTVeNwUn93Zl5vbkjRnHgiD7OotPcpmTGIx+wvnuetePZErEGXHfplDdAK02/GeB6JdZp2k8Jg9kIsF8Taka+jjVjNwqXuuN42HuuA6OtsmkyeeGXrSMCU=
    - secure: Fb0YtztU8zdN3ejeEwf//9wLbWCCe7i7H6e/rzIJ6ti2KBHmP7KpZnA4tpp3tpnBzIq4suRN2XBOV/UzGf6aS8tWV1ybI+y7ltyb0g2PAskZ/4wrZksN1D6kD+pXQUXkFGavL0J0enQlCz+Pl4J6bk4Ri8+dgtE5WuS8tlf9kIadWaau9hA2PEub6RwoBBliSAlodhqc34cQIpP7fg9L9fc3tlzTCwKm820xbPyAxKlH6/Se04L3+A9+eWA35PvexoSPMls2KKFL971+JbrCq6TtYd4MOOGtTzCHvH5e6evCXUWI+kkolhDoUWWSWYWVB8JnaI79Y4Kdbzd1kHU0dir9VIm4j+6pf1oA9PYa8ywudzAqbdLutjnB/pluwhw5EqBmViu732D7kSB4irwmmEQIr96mCusuq0J0U8znDHTmT0Eqr2F3IKZGNjJgOd7+ySlBLLgkvPIAYwkMo2c+j+8YyTrSF4chM7u6ds7xaoM+VASkgHA/YcuB1awqmV3CkG1vfl22wLdOQwpoG9fg7q3cDnBU1HymCoDvIgVffl06Qhdjhfe/1aMj/dmINAySsTSCc1CW/sTdxm8Np1cgL1JKtqkLZGYMeocmxNb7AkFNdXUUT30vcNFCiu53xClFhLsf+RpkbQbZ8oJmgCDle0ss2QZgZP1B5h336OtaNX4=
